=== COURT ===

= TMPH
&SCENE:TMPH_Assistant
&ACTOR:Dan
&SCENE:TMPH_Judge
&ACTOR:Brent_Judge
&SCENE:TMPH_Court
&SET_ACTOR_POSITION:1,Arin
&SET_ACTOR_POSITION:2,Ross
&SET_ACTOR_POSITION:3,Tutorial_Boy

-> DONE