=== Failures ===
    = TMPH
        &SET_GAME_OVER_SCRIPT:TMPH_GameOver
        &ADD_FAILURE_SCRIPT:TMPH_FAIL_1
        &ADD_FAILURE_SCRIPT:TMPH_FAIL_2
        &ADD_FAILURE_SCRIPT:TMPH_FAIL_3
        &ADD_FAILURE_SCRIPT:TMPH_FAIL_4
        -> DONE