=== COURT_TMPH ===

&HIDE_TEXTBOX
&SCENE:TMPHAssistant
&ACTOR:Dan
&SCENE:TMPHJudge
&ACTOR:JudgeBrent
&SCENE:TMPHCourt
&SET_ACTOR_POSITION:Defense,Arin
&SET_ACTOR_POSITION:Witness,Ross
&SET_ACTOR_POSITION:Prosecution,TutorialBoy

-> DONE