=== COURT_TMPH ===

&HIDE_TEXTBOX
&SCENE:TMPHAssistant
&ACTOR:Dan
&SCENE:TMPHJudge
&ACTOR:JudgeBrent
&SCENE:TMPHCourt
&SET_ACTOR_POSITION:1,Arin
&SET_ACTOR_POSITION:2,Ross
&SET_ACTOR_POSITION:3,TutorialBoy

-> DONE